apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: fedexapp
        image: fedexcr001.azurecr.io/fedexmodel
        ports:
        - containerPort: 5000
